modLoader = "javafml"
loaderVersion = "[31,)"
license = "BSD 3-Clause License"
issueTrackerURL = "https://github.com/gabeernie/Eidolon-Addon/issues"
[[mods]] #mandatory

modId = "apocrypha" #mandatory

version = "1.16.3-0.1.0" #mandatory

displayName = "Apocrypha" #mandatory

logoFile = "examplemod.png" #optional

credits = "Thanks to Lich!" #optional

authors = "Lich" #optional

description = '''
An addon mod for Eidolon by elucent
'''
[[dependencies.apocrypha]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[31,)" #mandatory
ordering = "NONE"
side = "BOTH"
# Here's another dependency
[[dependencies.apocrypha]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.3]"
ordering = "NONE"
side = "BOTH"
[[dependencies.apocrypha]]
modId = "eidolon"
mandatory = true
versionRange = "[0.2.7,)"
ordering = "NONE"
side = "BOTH"
